#[[
  cdefine ICE_CPU_IMPL
  cinclude "\"ice_cpu.h\""
]]
global ice_cpu_arch: type <cimport, nodecl, using> = @enum(cint) {
  ICE_CPU_ARCH_NONE = -1,
  ICE_CPU_ARCH_X86 = 0,
  ICE_CPU_ARCH_X86_64 = 1
}
global function ice_cpu_cores_count(): cuint <cimport, nodecl> end
global function ice_cpu_get_arch(): ice_cpu_arch <cimport, nodecl> end
global function ice_cpu_name(): cstring <cimport, nodecl> end
