name: Build

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Update Permissions
      shell: bash
      run: |
        chmod +x ${{ github.workspace }}/check_packages.sh ${{ github.workspace }}/build.sh
    
    - name: Toolchain Checks
      shell: bash
      run: ${{ github.workspace }}/check_packages.sh

    - name: Build (Microsoft Windows, Linux)
      shell: bash
      run: |
        ${{ github.workspace }}/build.sh
        
        cd ${{ github.workspace }}/ice_libs_builds
        zip -r ice_libs_builds.zip *
        
    - name: Uploading Artifacts
      uses: actions/upload-artifact@v2
      with: 
          name: ice_libs_builds
          path: ${{ github.workspace }}/ice_libs_builds/ice_libs_builds.zip
